# Docker Compose para el Entorno de Desarrollo de Aurora Nova

services:
  db:
    # Imagen oficial de PostgreSQL 18 con Alpine Linux, ligera y eficiente.
    image: postgres:18-alpine3.22
    container_name: aurora-nova-db
    restart: unless-stopped

    # Variables de entorno para la configuración de la base de datos.
    # ADVERTENCIA: Usar un sistema de gestión de secretos para producción.
    environment:
      POSTGRES_USER: aurora_user
      POSTGRES_PASSWORD: changeme_in_production
      POSTGRES_DB: aurora_nova_db
      TZ: America/El_Salvador
      LANG: es_SV.UTF-8

    # Mapeo de puertos: El puerto 5432 del contenedor se expone en el puerto 5432 del host.
    # Si tienes otro PostgreSQL corriendo localmente, puedes cambiar el puerto del host (ej. "5433:5432").
    ports:
      - "5432:5432"

    # Volumen para persistir los datos de la base de datos entre reinicios del contenedor.
    volumes:
      - aurora-nova-db-data:/var/lib/postgresql/data

  app:
    image: docker.io/byteflowsivar/aurora-nova:0.0.1
    container_name: aurora-nova-app
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      TZ: America/El_Salvador
      LANG: es_SV.UTF-8
      DATABASE_URL: "postgresql://aurora_user:changeme_in_production@db:5432/aurora_nova_db"
      AUTH_SECRET: "dev-secret-key-change-this-in-production-aurora-nova-2025"
      # Url de la aplicación
      NEXTAUTH_URL: "http://aurora.nova.local"
      # Configuración de autenticación
      AUTH_TRUST_HOST: true
      # Configuración de la aplicación
      APP_NAME: "Aurora Nova"
      APP_URL: "http://app:3000"
      # Configuración de logging
      LOG_LEVEL: "debug"

# Definición del volumen nombrado para la persistencia de datos.
volumes:
  aurora-nova-db-data:
